splitters:
  character_size:
    chunk_size: 1000
    chunk_overlap: 200

loaders:
  web:
    main_tagnames:
      - div
    main_classnames:
      - page
    title_tagnames:
      - div
    title_classnames:
      - page-title
    pagination_bar_tagnames:
      - div
    pagination_bar_classnames:
      - paginate_links
    article_title_tagnames:
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
    article_title_classnames:
      - emp-company

embedders:
  hugging_face:
    model_name: hiieu/halong_embedding

vector_stores:
  weaviate:
    host: weaviate
    port: 8080
    grpc_port: 50051
    collection_name: Document

ingestion:
  run: True
  pdf_paths:
    - data/raw/De-an-tuyen-sinh-DHQG-2023-QHI.pdf
    - data/raw/Signed.QHI_De-an-TS-DHCQ-nam-2024.pdf
    - data/raw/Thong-tin-tuyen-sinh-DHCQ-nam-2025-QHI.pdf
  link_paths:
    - data/raw/links.json
  faq_paths:
    - data/raw/faq.json

retriever:
  k: 5
  
summary:
  model_name: qwen/qwen3-4b:free

answer:
  model_name: qwen/qwen3-235b-a22b:free

intent_classification:
  model_name: qwen/qwen3-8b:free

memory:
  ttl: 900