services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - weaviate
  
  weaviate:
    image: semitechnologies/weaviate:1.32.2
    container_name: admission-chatbot-weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      CLUSTER_HOSTNAME: localhost
    volumes:
      - weaviate-data:/var/lib/weaviate
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  weaviate-data:
    name: admission-chatbot-weaviate-data